- hosts: all
  become: true

  roles:
    # - { role: os_hostname_display, when: "inventory_hostname in groups['all']" }
    # - { role: os_pkg_rm, when: "inventory_hostname in groups['worker']" }
    # - { role: os_hosts_mod, when: "inventory_hostname in groups['worker']" }
    # - { role: os_hosts_cp, when: "inventory_hostname in groups['worker']" }
    # - { role: os_hostname_set, when: "inventory_hostname in groups['worker']" }
    # - { role: os_ssh_auth, when: "inventory_hostname in groups['worker']" }
    #
<<<<<<< HEAD
    - { role: docker_install, when: "inventory_hostname in groups['k8s_node']" }
    - { role: os_usr_create, when: "inventory_hostname in groups['k8s_node']" }
    # 
=======
<<<<<<< HEAD
    # - { role: docker_install, when: "inventory_hostname in groups['k8s_node']" }
    # - { role: os_usr_create, when: "inventory_hostname in groups['k8s_node']" }
    # # 
    # - { role: os_swap_disable, when: "inventory_hostname in groups['k8s_node']" } 
    # - { role: k8s_install, when: "inventory_hostname in groups['k8s_node']" }
    # - { role: k8s_init, when: "inventory_hostname in groups['master']" }
    # - { role: k8s_kubeconfig, when: "inventory_hostname in groups['master']" }
    # - { role: k8s_flannel, when: "inventory_hostname in groups['master']" }
    # - { role: k8s_join_cmd, when: "inventory_hostname in groups['master']" }
    # - { role: k8s_join_node, when: "inventory_hostname in groups['worker']" }
    # - { role: k8s_autocompletion, when: "inventory_hostname in groups['controller']" }
    # - { role: os_lsblk, when: "inventory_hostname in groups['k8s_node']" }
    # 
    # - { role: helm3_install, when: "inventory_hostname in groups['master']" }
    # - { role: k8s_ingress_nginx, when: "inventory_hostname in groups['master']" }
    # - { role: cert-manager, when: "inventory_hostname in groups['master']" }
=======
    - { role: docker_install, when: "inventory_hostname in groups['k8s_node']" }
    - { role: os_usr_create, when: "inventory_hostname in groups['k8s_node']" }
    # 
>>>>>>> b81020731c7b19826f858f1dc17a801434b37aac
    - { role: os_swap_disable, when: "inventory_hostname in groups['k8s_node']" } 
    - { role: k8s_install, when: "inventory_hostname in groups['k8s_node']" }
    - { role: k8s_init, when: "inventory_hostname in groups['master']" }
    - { role: k8s_kubeconfig, when: "inventory_hostname in groups['master']" }
    - { role: k8s_flannel, when: "inventory_hostname in groups['master']" }
    - { role: k8s_join_cmd, when: "inventory_hostname in groups['master']" }
    - { role: k8s_join_node, when: "inventory_hostname in groups['worker']" }
    - { role: k8s_autocompletion, when: "inventory_hostname in groups['controller']" }
    - { role: os_lsblk, when: "inventory_hostname in groups['k8s_node']" }
    
    - { role: helm3_install, when: "inventory_hostname in groups['master']" }
    - { role: k8s_ingress_nginx, when: "inventory_hostname in groups['master']" }
    - { role: cert-manager, when: "inventory_hostname in groups['master']" }
<<<<<<< HEAD
=======
>>>>>>> add rook storage cluster with ceph
>>>>>>> b81020731c7b19826f858f1dc17a801434b37aac
    # - { role: prometheus, when: "inventory_hostname in groups['master']" }
    # - { role: kubeseal, when: "inventory_hostname in groups['master']" }
    #
    # - { role: nginx_server, when: "inventory_hostname in groups['webserver']" }
    #
    # ######## Test ########
    # - { role: test, when: "inventory_hostname in groups['master']" }
    #
    # ######## Destroy Kubernetes ########
<<<<<<< HEAD
    # - { role: k8s_destroy, when: "inventory_hostname in groups['k8s_node']" }
=======
<<<<<<< HEAD
    - { role: k8s_destroy, when: "inventory_hostname in groups['k8s_node']" }
=======
    # - { role: k8s_destroy, when: "inventory_hostname in groups['k8s_node']" }
>>>>>>> add rook storage cluster with ceph
>>>>>>> b81020731c7b19826f858f1dc17a801434b37aac
