---
# tasks file for k8s_usr_grant
- name: Setup kubeconfig for ubuntu user
  command: "{{ item }}"
  with_items:
   - mkdir -p /home/ubuntu/.kube
   - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
   - chown -R ubuntu:ubuntu /home/ubuntu/.kube
