---
# tasks file for docker_install

- name: Install pre-requisite packages
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    state: present
  
- name: Install Docker
  package:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages}}"
  # notify:
  # - start docker 
