---
# tasks file for os_lsblk
- name: Run lsblk on all nodes
  command: lsblk
  register: cmd_reg
- name: "lsblk stdout"
  debug:
    msg: "{{ cmd_reg.stdout.split('\n') }}"

- name: Collect only facts about hardware
  setup:
    gather_subset:
    - hardware

- name: Output disks
  debug:
    var: hostvars[inventory_hostname].ansible_devices.keys() | map('regex_search', 'sd.*') | select('string') | list
